### PR TITLE
Header image

### PR DESCRIPTION
**Pull request by jpdefrutos**
Frist attempt for a header image

### CODE REVIEW

**Review by andreped — COMMENTED** [review]
Wow! Great figure! I really like it! Not sure if it is _exactly_ what I wanted, but it is pretty darn close.

Can make some further comments and discuss ideas tomorrow.

**Comment by andreped** [comment]
Maybe a different color scheme might be cool. Like [synthwave](https://www.google.com/search?q=synthwave&sxsrf=APwXEdeLJ8BqHIInjNe2bTDM7JoTNXXbIA:1681417595663&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiKxYjU2Kf-AhWCyosKHRFqBkgQ_AUoAXoECAEQAw&cshid=1681417632058595&biw=1920&bih=969&dpr=1) maybe? I really like it.

**Comment by jpdefrutos** [comment]
From our discussions, I took you are secretly in love with MATLAB, hence the surface :)

**Comment by andreped** [comment]
> From our discussions, I took you are secretly in love with MATLAB, hence the surface :)

See: https://github.com/andreped/andreped/blob/870b44d0823cab9e8f2bfe8c4dca219440ee1418/README.md?plain=1#L7

image

**Comment by andreped** [comment]
For future reference, when making commits which don't involve code changes, you can just add `[no ci]` at the end of the commit message to avoid unnecessary CIs being ran, which was the case for this PR.

**Comment by jpdefrutos** [comment]
> For future reference, when making commits which don't involve code changes, you can just add `[no ci]` at the end of the commit message to avoid unnecessary CIs being ran, which was the case for this PR.

Ty! :)

**Comment by jpdefrutos** [comment]
Uploaded new header versions in commit ecf8fb28c10ee5622fff5fa03ae24c76e276ba76

**Review by andreped — CHANGES_REQUESTED** [review]
I think they might be _too_ complex. I was looking for something more minimalistic.

You had some nice drafts earlier. Perhaps somewhere in the middle?

Perhaps the old one was fine, it just needed some of the same ideas as this one, excluding the grid maybe?

**Comment by jpdefrutos** [comment]
Perhaps this? fb383f960c69b689dd8163d1b188d7f7a36b3048

**Comment by andreped** [comment]
Thats neat! Perhaps just missing the same colour palette as the first one you made? Dont need a grid but some neato colours comes a long way.

**Comment by jpdefrutos** [comment]
Perhaps? 397976f79106ad3966eb056b7dbfcfd4f2957415

**Comment by andreped** [comment]
LGTM! Great job! :]

There will likely be some minor modifications in the near future, but it is good enough for now.

**Pull request merged**
